# DrakesTech runtime settings.
# These options control guide behavior and first-join UX.

guide:
  # Give the guide book automatically the first time a player joins.
  auto-give-on-first-join: true

  # Open guide when player right-clicks with the guide book.
  # [DANGER] If disabled, players need command/menu access from another source.
  open-on-right-click: true

  # Main title for module selector inventory.
  main-title: "<gold><b>DrakesTech Modules</b></gold>"

  book:
    # Material used for the guide book item.
    material: WRITTEN_BOOK

    # Display name (MiniMessage supported).
    name: "<gradient:gold:red><b>DrakesTech Guide</b></gradient>"

    # Lore lines (MiniMessage supported).
    lore:
      - "<gray>Right click to open modules.</gray>"
      - "<dark_gray>Powered by DrakesCraft Labs</dark_gray>"

research:
  # Enable progression locks for guide entries.
  # If false, all guide entries are visible and unlocked for everyone.
  enabled: true

  unlock-costs:
    # Base XP level cost to unlock a full module from the guide.
    # This applies when the module is locked and no per-module cost is defined.
    module-levels: 20

    # Base XP level cost to unlock one guide entry.
    # This applies when an entry is locked and no per-entry cost is defined.
    entry-levels: 8

  # Modules unlocked by default for every player.
  # Format: module id (lowercase).
  default-unlocked-modules:
    - machines

  # Specific entries unlocked by default.
  # Format: "module|entry" or "module|*" (unlock full module).
  # [DANGER] Keep IDs in sync with tech-content.yml.
  default-unlocked-entries: []

automation:
  item-transfer:
    # Enable automatic item transport between adjacent DrakesTech machines.
    enabled: true

    # Ticks between each transfer cycle.
    # Recommended: 5-20. Lower values move items faster but cost more CPU.
    interval-ticks: 10

    # Maximum amount of items moved per source->target cycle.
    # [DANGER] Very high values can increase hopper-like throughput and server load.
    max-items-per-move: 8

  tech-storage:
    # If true, Tech Storage Chest accepts only DrakesTech items and machine items.
    # If false, it can store vanilla and any other plugin items too.
    only-plugin-items: true
