name: DrakesTech
version: 1.0
main: me.jackstar.drakestech.DrakesTechPlugin
api-version: '1.20'
authors: [JackStar]
description: Tech machines and energy system for DrakesCraft
softdepend: [PlaceholderAPI, Vault, Slimefun]
commands:
  drakestech:
    description: Admin command for DrakesTech
    usage: /drakestech <give|guide|search|research|list|diagnostics|reload>
    permission: drakestech.admin
    aliases: [dtech, drtech]
permissions:
  drakestech.admin:
    description: Allows use of DrakesTech admin command
    default: op
